/* Auto-generated by scripts/build-scenarios.js — do not edit by hand */
window.SCENARIOS = [
  {
    "id": "01",
    "slug": "01-clone-and-find-working-branch",
    "title": "Clone repo và xác định branch đang được code chính",
    "short": "Clone & tìm branch chính",
    "symptom": "I don't know which branch to use",
    "videos": {
      "cli": "video/clone-voi-ssh.mp4",
      "cursor-vscode": "video/clone-voi-pat.mp4",
      "github-desktop": null,
      "fork": null
    },
    "takeaway": "Luôn kiểm tra default branch, hoạt động gần đây (PR/CI/commit), và quy trình branching của team trước khi bắt đầu code."
  },
  {
    "id": "02",
    "slug": "02-create-branch-after-coding-on-main",
    "title": "Code trên main rồi mới phát hiện chưa tạo branch",
    "short": "Quên tạo branch (trên main)",
    "symptom": "I accidentally coded on main",
    "videos": {
      "cli": "video/example-2.mp4",
      "cursor-vscode": null,
      "github-desktop": null,
      "fork": null
    },
    "takeaway": "Uncommitted changes đi theo khi bạn `git switch -c`. Nếu đã commit trên main chưa push: tạo branch tại HEAD rồi reset main về trước commit đó."
  },
  {
    "id": "03",
    "slug": "03-local-commits-and-remote-commits",
    "title": "Local commits + remote commits cùng tồn tại",
    "short": "Local + remote diverge",
    "symptom": "Pull says branches have diverged",
    "videos": {
      "cli": "video/example-3.mp4",
      "cursor-vscode": null,
      "github-desktop": null,
      "fork": null
    },
    "takeaway": "Fetch trước → xem graph → chọn rebase (linear) hoặc merge → resolve → push (`--force-with-lease` nếu đã rebase branch đã publish)."
  },
  {
    "id": "04",
    "slug": "04-discard-uncommitted-changes",
    "title": "Bỏ changes chưa commit",
    "short": "Bỏ changes chưa commit",
    "symptom": "I want to remove my changes",
    "videos": {
      "cli": "video/example-4.mp4",
      "cursor-vscode": null,
      "github-desktop": null,
      "fork": null
    },
    "takeaway": "`git restore` hoàn tác working tree về HEAD. Nếu chưa chắc → `git stash` an toàn hơn. Staged cần `--staged` rồi mới restore nội dung."
  },
  {
    "id": "05",
    "slug": "05-amend-last-commit",
    "title": "Commit thiếu file → thêm vào commit vừa tạo",
    "short": "Amend commit thiếu file",
    "symptom": "I forgot a file in my commit",
    "videos": {
      "cli": "video/example-5.mp4",
      "cursor-vscode": null,
      "github-desktop": null,
      "fork": null
    },
    "takeaway": "Amend thay thế commit cuối (đổi hash). Chỉ dùng khi commit còn local (hoặc branch riêng bạn kiểm soát)."
  },
  {
    "id": "06",
    "slug": "06-remove-files-from-git",
    "title": "Lỡ commit file cần nằm trong .gitignore",
    "short": "Lỡ commit .env / dump",
    "symptom": "I committed .env",
    "videos": {
      "cli": "video/example-6.mp4",
      "cursor-vscode": null,
      "github-desktop": null,
      "fork": null
    },
    "takeaway": "Stop tracking bằng `git rm --cached` + `.gitignore`. Nếu đã push secret → **rotate/revoke ngay**, rồi mới clean history theo quy trình team."
  },
  {
    "id": "07",
    "slug": "07-go-back-to-old-commit",
    "title": "Muốn quay lại commit cũ",
    "short": "Quay lại commit cũ",
    "symptom": "I want to go back to an old commit",
    "videos": {
      "cli": "video/example-7.mp4",
      "cursor-vscode": null,
      "github-desktop": null,
      "fork": null
    },
    "takeaway": "Đã push/shared → ưu tiên `git revert`. Local chưa share → `reset` có thể phù hợp. Training: hiểu sự khác biệt history."
  },
  {
    "id": "08",
    "slug": "08-resolve-merge-conflict",
    "title": "Merge Request / PR bị conflict",
    "short": "PR / MR bị conflict",
    "symptom": "PR has conflicts",
    "videos": {
      "cli": "video/example-8.mp4",
      "cursor-vscode": null,
      "github-desktop": null,
      "fork": null
    },
    "takeaway": "Fetch → rebase/merge `main` vào feature → sửa conflict có chủ đích → continue → test → push (`force-with-lease` nếu rebase)."
  },
  {
    "id": "09",
    "slug": "09-selectively-merge-features",
    "title": "Chỉ merge một số feature từ dev sang main",
    "short": "Merge chọn lọc (cherry-pick)",
    "symptom": "I only want to merge some features",
    "videos": {
      "cli": "video/example-9.mp4",
      "cursor-vscode": null,
      "github-desktop": null,
      "fork": null
    },
    "takeaway": "Ngắn hạn: `cherry-pick` các commit/feature đã duyệt. Dài hạn: mỗi feature một branch + PR riêng vào `main`."
  }
];
